name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest

      - run: shards install
      - run: crystal spec

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
